### ISSUE TITLE
build.gradle says maven?

### ISSUE THREAD

**Issue by GantMan** [HipByte/motion-gradle#11]
Hey!   So I'm floundering on why this isn't working.

I'm trying to include this gradle repo:   https://github.com/alexbbb/android-upload-service

I'm including with this: 

``` ruby
  app.gradle do
    repository "https://github.com/alexbbb/android-upload-service"
  end
```

I perform the other steps required in the Github readme (inconsequential to this ticket).  But I'm unable to access the Gradle class.  `Com::Alexbbb::Uploadservice::UploadService.NAMESPACE` or any permutation of those constants cannot be found.

In my build.gradle, it says something about maven.  But I can't seem to see how Gradle is pulling this class in.   

``` ruby
repositories {

    maven {
      url "/Users/gantman/android-rubymotion/sdk/extras/android/m2repository/"
    }


    maven {
      url "/Users/gantman/android-rubymotion/sdk/extras/google/m2repository/"
    }


    maven {
      url "https://github.com/alexbbb/android-upload-service"
    }

  mavenCentral()
}
```

Any hep would be greatly appreciated.   Am I misunderstanding some step?

**Comment by jjaffeux** [comment]
@GantMan hello :)

repository here is to be understood as a maven repository, I don't think "https://github.com/alexbbb/android-upload-service" is a valid maven repository.

**Comment by jjaffeux** [comment]
Also right now, motion-gradle doesn't support using a git repository as a library source, we could implement it using https://github.com/layerhq/gradle-git-repo-plugin

**Comment by GantMan** [comment]
I was tired and I saw repository, lol.   I understand now.   Yes, I think it would be nice to support github, but that's the first time I found a github repo with no gradle url.   Hopefully this isn't common.
