### ISSUE TITLE
gradle:install (& rake) Failing

### ISSUE THREAD

**Issue by fvonhoven** [HipByte/motion-gradle#17]
Cannot rake, getting this error:
![screen shot 2015-08-17 at 4 30 04 pm](https://cloud.githubusercontent.com/assets/10098988/9316843/4fdc84e4-44fd-11e5-8461-c3b828fe485a.png)

API 23 Installed through manager via motion android-setup.
Appears to be installed in Manager...

**Comment by jjaffeux** [comment]
@fvonhoven  It's a RubyMotion error, probably related to the fact that Marshmallow has only been released few hours ago and is not yet supported.
