### ISSUE TITLE
RubyMotion 4.0 Breaks AAR support?

### ISSUE THREAD

**Issue by skellock** [HipByte/motion-gradle#19]
I'm having some issues building our project now that we've upgraded to RM 4.0.

It looks like the `/Library/RubyMotion/lib/motion/project/template/android/config.rb` line 430 is looking for a new directory called `versionized_build_dir`.

Are you seeing the same thing?

**Comment by skellock** [comment]
Here's the silly fix that gets me building at least.   Basically giving the build chain a 2nd chance to generate the bridge files (the way it used to be).    The fix is in between the "-- SAD PANDA" blocks.

```

    def vendored_bs_files(create=true)
      @vendored_bs_files ||= begin
        vendored_projects.map do |proj|
          jar_file = proj[:jar]
          bs_file = File.join(versionized_build_dir, File.basename(jar_file) + '.bridgesupport')
          if create and (!File.exist?(bs_file) or File.mtime(jar_file) > File.mtime(bs_file))
            App.info 'Create', bs_file
            sh "#{bin_exec('android/gen_bridge_metadata')} -o \"#{bs_file}\" \"#{jar_file}\""
          else # -- SAD PANDA
            bs_file = File.join(File.dirname(jar_file), File.basename(jar_file) + '.bridgesupport')
            if create and (!File.exist?(bs_file) or File.mtime(jar_file) > File.mtime(bs_file))
              App.info 'Create', bs_file
              sh "#{bin_exec('android/gen_bridge_metadata')} -o \"#{bs_file}\" \"#{jar_file}\""
            end
            # -- SAD PANDA
          end 
          bs_file
        end
      end
    end
```

**Comment by jjaffeux** [comment]
@skellock Hi, sorry might be missing something, but where is it related to motion-gradle ?

**Comment by skellock** [comment]
In our project, RM 4.0 wasn't able to build the bridgesupport files for anything included via motion-gradle.

I spun up a new project and brought in an aar, and it found the bridgesupport file no problem.

I thought maybe `motion-gradle` needed to adjust where it places its extracted aar's.

**Comment by jjaffeux** [comment]
@skellock @GantMan ok, reopening this, do you think we should handle this at motion-gradle level ?

**Comment by skellock** [comment]
Yep.  `versionized_build_dir` is where RM 4 starts looking now.  We should make ourselves available there.

I didn't look at what is required (or even where `versionized_build_dir` is defined).  I just needed to get a client up & running on RM 4's codebase due to memory leaks in RM 3.13.

I'm on vacation week 1 of 2, but if this issue is still outstanding when I'm back, I'll jump on it.

Thanks for re-opening.

**Comment by jjaffeux** [comment]
@skellock I would just need a project not working on RM4 please, I can't reproduce this.

**Comment by GantMan** [comment]
@skellock  is on vacation this week.  I'll try to cook something up for ya.

**Comment by GantMan** [comment]
@jjaffeux here's the sample project.

https://github.com/GantMan/failed_gradle_example

The error looks like this:  
![image](https://cloud.githubusercontent.com/assets/997157/10081932/fb739e00-62bc-11e5-808c-8981c853cac6.png)

This is 100% fixed when you apply the patch @skellock demonstrates above.

**Comment by jjaffeux** [comment]
@GantMan awesome, I will check this, thx.

**Comment by jjaffeux** [comment]
Should be good @GantMan @skellock , let me know how it goes for you and thanks for your help;)
