### ISSUE TITLE
Use auto-detection of gradle location

### ISSUE THREAD

**Issue by jamonholmgren** [HipByte/motion-gradle#2]
Here: https://github.com/jjaffeux/motion-gradle/blob/master/lib/motion/project/gradle.rb#L26

Wouldn't this work?

``` ruby
@gradle_path = '/usr/bin/env gradle'
```

**Comment by jjaffeux** [comment]
Are we sure we will always have `/usr/bin/env` ?

Your solution is probably better than the current one, just not sure of the implications.

**Comment by jamonholmgren** [comment]
Yeah, I use it for ProMotion's binary, and nobody has complained yet.

**Comment by jjaffeux** [comment]
Ok I will try your suggestion and we will see... Should be ok, thx.
