### ISSUE TITLE
Support for compile time dependencies

### ISSUE THREAD

**Issue by skellock** [HipByte/motion-gradle#24]
There are some libraries like NewRelic which rely on compile time dependencies.

**Comment by jjaffeux** [comment]
@skellock hi, could you point me to what would be needed to support this ?

**Comment by mixflame** [comment]
Seconding this. I can provide back up info later when I try again with libpd.

**Comment by jjaffeux** [comment]
@jsilverMDX please do, a failing app example would be perfect

**Comment by skellock** [comment]
Sorry I haven't followed up.  Super busy.  :(

**Comment by mixflame** [comment]
Cool. I will get on it ASAP. The app will be private, but I will upload/send it to you via your preferred means. It's a synthesizer which relies on libpd.

**Comment by jjaffeux** [comment]
@skellock no worries ;)

@jsilverMDX a private repo that you share with me or you can send it via email, it's on my github profile

**Comment by mixflame** [comment]
@jjaffeux cool. I will share you a repo. Break for now, but I'm on this.

**Comment by jjaffeux** [comment]
@jsilverMDX take your time, probably won't watch it today

**Comment by mixflame** [comment]
no problem. might take me a week or so because I haven't made that app yet. but it will only be a translation of iOS code.

**Comment by mixflame** [comment]
Well it seems at this attempt things are looking more successful. My problems were with AARs before they were supported and I'm not sure if @skellock's issue is the same.

**Comment by jjaffeux** [comment]
@jsilverMDX good to hear :)

**Comment by jjaffeux** [comment]
Closing for now. @jsilverMDX @skellock feel free to reopen if needed.
