### ISSUE TITLE
constructor MainActivity() is already defined in class MainActivity

### ISSUE THREAD

**Issue by acrogenesis** [HipByte/motion-gradle#25]
When adding this specific gradle dependency `'com.danikula:videocache:2.3.1'` the .java file generated for MainActivity declares `public MainActivity() { super(); }` twice. 

build/Development-19/java/com/yourcompany/hello/MainActivity.java

``` java
    // This file has been generated automatically. Do not edit.
    package com.yourcompany.hello;
    import com.rubymotion.*;
    public class MainActivity extends android.app.Activity {
        public MainActivity() { super(); }
        public MainActivity() { super(); }
        public native void onCreate(android.os.Bundle arg0);
        static {
            java.lang.System.loadLibrary("payload");
        }
    }
```

Code Sample: https://github.com/acrogenesis/rubymotion-constructor-bug

http://community.rubymotion.com/t/mainactivity-is-already-defined-in-class-mainactivity/1127

**Comment by jjaffeux** [comment]
@acrogenesis Hi, could you explain why you think it's related to motion-gradle ? motion-gradle doesn't generate this MainActivity.java

**Comment by acrogenesis** [comment]
I'm not sure it's motion-gradle the responsible but it is related because I was able to build the jar and libs myself using the `./gradlew jarRelease` and adding it to RubyMotion as an external library. So basically if I add it using the 

``` ruby
app.gradle do
    dependency 'com.danikula:videocache:2.3.1'
end
```

It fails.

**Comment by jjaffeux** [comment]
Please look at http://community.rubymotion.com/t/rubymotion-bug-mainactivity-is-already-defined-in-class-mainactivity/1127/2 I have answered here, thx.
