### ISSUE TITLE
Rake aborted due to bridgesupport

### ISSUE THREAD

**Issue by emtee** [HipByte/motion-gradle#26]
I am facing this issue without any success fixing it what so ever. I started facing this ever since is tried importing 'org.apache.httpcomponents:httpclient:4.4.1'

rake device
    Create ./build/Development-22/commons-codec-1.9.jar.bridgesupport
Could not find rake-10.1.0 in any of the sources
Run `bundle install` to install missing gems.
rake aborted!
Command failed with status (7): [/Library/RubyMotion/bin/android/gen_bridge...]
/Library/RubyMotion/lib/motion/project/template/android/config.rb:440:in `block in vendored_bs_files'
/Library/RubyMotion/lib/motion/project/template/android/config.rb:435:in`map'
/Library/RubyMotion/lib/motion/project/template/android/config.rb:435:in `vendored_bs_files'
/Library/RubyMotion/lib/motion/project/template/android.rb:215:in`block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:211:in `each'
/Library/RubyMotion/lib/motion/project/template/android.rb:211:in`block in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:758:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:758:in`each'
/Library/RubyMotion/lib/motion/project/template/android.rb:758:in `block in <top (required)>'
Tasks: TOP => build
(See full trace by running task with --trace)

Any help is appreciated.

**Comment by jjaffeux** [comment]
@emtee Please fix your issue with rake before, it's not related to motion-gradle.

Could not find rake-10.1.0 in any of the sources

**Comment by emtee** [comment]
@jjaffeux Thanks for your quick response. I suspected the same, but rake seems to work fine. Other rake tasks like 'rake clean', 'rake gradle:install' etc just work.
Only when i run the task "rake device", it ends up throwing this error. This error popped up after I added motion-gradle & added those dependencies.

Please let me know if you have any suggestions on this.
