### ISSUE TITLE
Android Support Material Design

### ISSUE THREAD

**Issue by rewathkafley** [HipByte/motion-gradle#27]
For Some reason i am unable to use <b>Material Design Theme</b> from the Vendor Support Libraries.
It seems the compile time lookup for dependency is failing for some reason for motion-gradle dependencies.

![screen shot 2015-11-20 at 12 56 40 pm](https://cloud.githubusercontent.com/assets/9987781/11325149/a94f4eb6-9170-11e5-98d2-bee70933a5bb.png)

**Comment by jjaffeux** [comment]
@kafs1696 Hi, can you provide a sample failing project please

**Comment by jjaffeux** [comment]
@kafs1696 closing until answer
