### ISSUE TITLE
Creating gems that use motion-gradle

### ISSUE THREAD

**Issue by darinwilson** [HipByte/motion-gradle#4]
I'm writing a gem that integrates a 3rd party Java lib, and I'm using motion-gradle to manage those dependencies within the gem. 

If I create a project that uses the gem, then run `rake gradle:install` within the project, it doesn't seem to pick up the dependencies declared in the gem. Is that expected behavior at this point? How does this work with CocoaPods?

**Comment by jjaffeux** [comment]
@darinwilson It should work, can you show me some code ? 

For example this gem is using motion-maven https://github.com/jannishuebl/couchmotion and I see no reason it wouldn't work with motion-gradle

**Comment by darinwilson** [comment]
@jjaffeux Ah - my mistake. I hadn't put the dependencies in the right place in the code. Thanks for pointing me to the couchmotion example. That set me straight! :)
