### ISSUE TITLE
Version 1.1.0 is still unreleased

### ISSUE THREAD

**Issue by acrogenesis** [HipByte/motion-gradle#5]
I've been trying to install a gradle dependency looking at the Readme and I couldn't get it to work. It seems the latest version on rubygems is `1.0.5`

**Comment by jjaffeux** [comment]
yes I need the releaqe of rm 3.11 to do a proper new release, also I dont have a computer til monday, so expect a new gem release next week.

Envoyé de mon iPhone

**Comment by acrogenesis** [comment]
Thanks @jjaffeux my temp fix was doing `gem 'motion-gradle', github: 'HipByte/motion-gradle'` if anyone else has this problem :+1:

**Comment by jjaffeux** [comment]
@acrogenesis just released 1.11, let me know how it works for you ;)
