### ISSUE TITLE
Failed Gradle

### ISSUE THREAD

**Issue by GantMan** [HipByte/motion-gradle#7]
``` ruby
  app.gradle do
    #Android Universal image loader - https://android-arsenal.com/details/1/210
    dependency 'com.github.nostra13:Android-Universal-Image-Loader:v1.9.3'
  end
```

RESULT:
![screen shot 2015-05-21 at 9 59 30 am](https://cloud.githubusercontent.com/assets/997157/7751545/3da2f940-ffa0-11e4-81d9-b4352823f942.png)

**Comment by jjaffeux** [comment]
@GantMan  What about :

  app.gradle do
    dependency 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
  end

**Comment by GantMan** [comment]
I got it... I'm new to all this!

This was the fix:

``` ruby
app.gradle do
    repository 'https://jitpack.io'
    #Android Universal image loader - https://android-arsenal.com/details/1/210
    dependency 'com.github.nostra13:Android-Universal-Image-Loader:v1.9.3'
end
```

**Comment by GantMan** [comment]
ACTUALLY, your URL worked better... could you explain why?

I'm very interested.

**Comment by jjaffeux** [comment]
@GantMan I looked the wiki : https://github.com/nostra13/Android-Universal-Image-Loader/wiki/Quick-Setup And they use this setup.

Also when you define a dependency, gradle will look in maven central (and your local repositories, the one I asked you to check in android gui) : http://search.maven.org/#search%7Cga%7C1%7Ccom.nostra13.universalimageloader

If you try to search with you previous dependency, you won't find anything, it means maven central doesn't have this dependency (and motion-gradle won't find it with base setup). When you did repository 'https://jitpack.io' you add another repository to look for, and it happens this repository might have 'com.github.nostra13:Android-Universal-Image-Loader:v1.9.3'

It's like `source 'https://rubygems.com'`, you could add another private gem server for example.

**Comment by GantMan** [comment]
Thanks!
