### ISSUE TITLE
Support Java glue code and 3rd party gradle dependencies in RubyMotion gems

### ISSUE THREAD

**Issue by buzzware** [HipByte/motion-gradle#9]
The goal is to enable the creation of motion gems for common third party Java libraries using Android Studio. Java glue code is typically required, and would be best developed in the Android Studio environment with junit, breakpointing, single step debugging etc. The libraries would be attached via gradle. I'm not sure whether motion-gradle is currently supported in a gem.

Usage and development of the resulting gem would then be a smooth experience, and facilitate access to a vast array of third party Android libraries in RubyMotion.

**Comment by jjaffeux** [comment]
@buzzware Not sure to understand what you mean. Do you want to know if another gem uses motion-gradle and declares dependencies, will it work. Yes it should.
